//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeServices.serviceBeer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server/", ConfigurationName="serviceBeer.Beer")]
    public interface Beer {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getMethodsRequest", ReplyAction="http://server/Beer/getMethodsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsumeServices.serviceBeer.getMethodsResponse getMethods(ConsumeServices.serviceBeer.getMethodsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getMethodsRequest", ReplyAction="http://server/Beer/getMethodsResponse")]
        System.Threading.Tasks.Task<ConsumeServices.serviceBeer.getMethodsResponse> getMethodsAsync(ConsumeServices.serviceBeer.getMethodsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/HelloWorldRequest", ReplyAction="http://server/Beer/HelloWorldResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsumeServices.serviceBeer.HelloWorldResponse HelloWorld(ConsumeServices.serviceBeer.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/HelloWorldRequest", ReplyAction="http://server/Beer/HelloWorldResponse")]
        System.Threading.Tasks.Task<ConsumeServices.serviceBeer.HelloWorldResponse> HelloWorldAsync(ConsumeServices.serviceBeer.HelloWorldRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getCheapestRequest", ReplyAction="http://server/Beer/getCheapestResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsumeServices.serviceBeer.getCheapestResponse getCheapest(ConsumeServices.serviceBeer.getCheapestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getCheapestRequest", ReplyAction="http://server/Beer/getCheapestResponse")]
        System.Threading.Tasks.Task<ConsumeServices.serviceBeer.getCheapestResponse> getCheapestAsync(ConsumeServices.serviceBeer.getCheapestRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getCostliestRequest", ReplyAction="http://server/Beer/getCostliestResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsumeServices.serviceBeer.getCostliestResponse getCostliest(ConsumeServices.serviceBeer.getCostliestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getCostliestRequest", ReplyAction="http://server/Beer/getCostliestResponse")]
        System.Threading.Tasks.Task<ConsumeServices.serviceBeer.getCostliestResponse> getCostliestAsync(ConsumeServices.serviceBeer.getCostliestRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getPriceRequest", ReplyAction="http://server/Beer/getPriceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsumeServices.serviceBeer.getPriceResponse getPrice(ConsumeServices.serviceBeer.getPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getPriceRequest", ReplyAction="http://server/Beer/getPriceResponse")]
        System.Threading.Tasks.Task<ConsumeServices.serviceBeer.getPriceResponse> getPriceAsync(ConsumeServices.serviceBeer.getPriceRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getBeersRequest", ReplyAction="http://server/Beer/getBeersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsumeServices.serviceBeer.getBeersResponse getBeers(ConsumeServices.serviceBeer.getBeersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getBeersRequest", ReplyAction="http://server/Beer/getBeersResponse")]
        System.Threading.Tasks.Task<ConsumeServices.serviceBeer.getBeersResponse> getBeersAsync(ConsumeServices.serviceBeer.getBeersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMethods", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getMethodsRequest {
        
        public getMethodsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMethodsResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getMethodsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getMethodsResponse() {
        }
        
        public getMethodsResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class HelloWorldRequest {
        
        public HelloWorldRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorldResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCheapest", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getCheapestRequest {
        
        public getCheapestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCheapestResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getCheapestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getCheapestResponse() {
        }
        
        public getCheapestResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCostliest", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getCostliestRequest {
        
        public getCostliestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCostliestResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getCostliestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getCostliestResponse() {
        }
        
        public getCostliestResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPrice", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getPriceRequest() {
        }
        
        public getPriceRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPriceResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public getPriceResponse() {
        }
        
        public getPriceResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBeers", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getBeersRequest {
        
        public getBeersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBeersResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getBeersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getBeersResponse() {
        }
        
        public getBeersResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BeerChannel : ConsumeServices.serviceBeer.Beer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BeerClient : System.ServiceModel.ClientBase<ConsumeServices.serviceBeer.Beer>, ConsumeServices.serviceBeer.Beer {
        
        public BeerClient() {
        }
        
        public BeerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BeerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BeerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BeerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeServices.serviceBeer.getMethodsResponse ConsumeServices.serviceBeer.Beer.getMethods(ConsumeServices.serviceBeer.getMethodsRequest request) {
            return base.Channel.getMethods(request);
        }
        
        public string[] getMethods() {
            ConsumeServices.serviceBeer.getMethodsRequest inValue = new ConsumeServices.serviceBeer.getMethodsRequest();
            ConsumeServices.serviceBeer.getMethodsResponse retVal = ((ConsumeServices.serviceBeer.Beer)(this)).getMethods(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeServices.serviceBeer.getMethodsResponse> ConsumeServices.serviceBeer.Beer.getMethodsAsync(ConsumeServices.serviceBeer.getMethodsRequest request) {
            return base.Channel.getMethodsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeServices.serviceBeer.getMethodsResponse> getMethodsAsync() {
            ConsumeServices.serviceBeer.getMethodsRequest inValue = new ConsumeServices.serviceBeer.getMethodsRequest();
            return ((ConsumeServices.serviceBeer.Beer)(this)).getMethodsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeServices.serviceBeer.HelloWorldResponse ConsumeServices.serviceBeer.Beer.HelloWorld(ConsumeServices.serviceBeer.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsumeServices.serviceBeer.HelloWorldRequest inValue = new ConsumeServices.serviceBeer.HelloWorldRequest();
            ConsumeServices.serviceBeer.HelloWorldResponse retVal = ((ConsumeServices.serviceBeer.Beer)(this)).HelloWorld(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeServices.serviceBeer.HelloWorldResponse> ConsumeServices.serviceBeer.Beer.HelloWorldAsync(ConsumeServices.serviceBeer.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeServices.serviceBeer.HelloWorldResponse> HelloWorldAsync() {
            ConsumeServices.serviceBeer.HelloWorldRequest inValue = new ConsumeServices.serviceBeer.HelloWorldRequest();
            return ((ConsumeServices.serviceBeer.Beer)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeServices.serviceBeer.getCheapestResponse ConsumeServices.serviceBeer.Beer.getCheapest(ConsumeServices.serviceBeer.getCheapestRequest request) {
            return base.Channel.getCheapest(request);
        }
        
        public string getCheapest() {
            ConsumeServices.serviceBeer.getCheapestRequest inValue = new ConsumeServices.serviceBeer.getCheapestRequest();
            ConsumeServices.serviceBeer.getCheapestResponse retVal = ((ConsumeServices.serviceBeer.Beer)(this)).getCheapest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeServices.serviceBeer.getCheapestResponse> ConsumeServices.serviceBeer.Beer.getCheapestAsync(ConsumeServices.serviceBeer.getCheapestRequest request) {
            return base.Channel.getCheapestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeServices.serviceBeer.getCheapestResponse> getCheapestAsync() {
            ConsumeServices.serviceBeer.getCheapestRequest inValue = new ConsumeServices.serviceBeer.getCheapestRequest();
            return ((ConsumeServices.serviceBeer.Beer)(this)).getCheapestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeServices.serviceBeer.getCostliestResponse ConsumeServices.serviceBeer.Beer.getCostliest(ConsumeServices.serviceBeer.getCostliestRequest request) {
            return base.Channel.getCostliest(request);
        }
        
        public string getCostliest() {
            ConsumeServices.serviceBeer.getCostliestRequest inValue = new ConsumeServices.serviceBeer.getCostliestRequest();
            ConsumeServices.serviceBeer.getCostliestResponse retVal = ((ConsumeServices.serviceBeer.Beer)(this)).getCostliest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeServices.serviceBeer.getCostliestResponse> ConsumeServices.serviceBeer.Beer.getCostliestAsync(ConsumeServices.serviceBeer.getCostliestRequest request) {
            return base.Channel.getCostliestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeServices.serviceBeer.getCostliestResponse> getCostliestAsync() {
            ConsumeServices.serviceBeer.getCostliestRequest inValue = new ConsumeServices.serviceBeer.getCostliestRequest();
            return ((ConsumeServices.serviceBeer.Beer)(this)).getCostliestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeServices.serviceBeer.getPriceResponse ConsumeServices.serviceBeer.Beer.getPrice(ConsumeServices.serviceBeer.getPriceRequest request) {
            return base.Channel.getPrice(request);
        }
        
        public double getPrice(string arg0) {
            ConsumeServices.serviceBeer.getPriceRequest inValue = new ConsumeServices.serviceBeer.getPriceRequest();
            inValue.arg0 = arg0;
            ConsumeServices.serviceBeer.getPriceResponse retVal = ((ConsumeServices.serviceBeer.Beer)(this)).getPrice(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeServices.serviceBeer.getPriceResponse> ConsumeServices.serviceBeer.Beer.getPriceAsync(ConsumeServices.serviceBeer.getPriceRequest request) {
            return base.Channel.getPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeServices.serviceBeer.getPriceResponse> getPriceAsync(string arg0) {
            ConsumeServices.serviceBeer.getPriceRequest inValue = new ConsumeServices.serviceBeer.getPriceRequest();
            inValue.arg0 = arg0;
            return ((ConsumeServices.serviceBeer.Beer)(this)).getPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeServices.serviceBeer.getBeersResponse ConsumeServices.serviceBeer.Beer.getBeers(ConsumeServices.serviceBeer.getBeersRequest request) {
            return base.Channel.getBeers(request);
        }
        
        public string[] getBeers() {
            ConsumeServices.serviceBeer.getBeersRequest inValue = new ConsumeServices.serviceBeer.getBeersRequest();
            ConsumeServices.serviceBeer.getBeersResponse retVal = ((ConsumeServices.serviceBeer.Beer)(this)).getBeers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeServices.serviceBeer.getBeersResponse> ConsumeServices.serviceBeer.Beer.getBeersAsync(ConsumeServices.serviceBeer.getBeersRequest request) {
            return base.Channel.getBeersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeServices.serviceBeer.getBeersResponse> getBeersAsync() {
            ConsumeServices.serviceBeer.getBeersRequest inValue = new ConsumeServices.serviceBeer.getBeersRequest();
            return ((ConsumeServices.serviceBeer.Beer)(this)).getBeersAsync(inValue);
        }
    }
}
